<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>XEFWarehouseManager</AssemblyName>
    <RootNamespace>XEFWarehouseManager</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LavaGang.MelonLoader" Version="0.7.3" />
  </ItemGroup>
</Project>